# Introducción

El efectivo es el recurso más importante de cualquier institución, por lo que es necesario una gestión adecuada para el funcionamiento normal y eficiente de esta. La planeación y proyección del flujo de efectivo es necesario, para ello es importante contar con una herramienta que permita maximizar y analizar la utilización de esos recursos, es por ello que a lo largo de este manual se describe a detalle el proceso para garantizar un adecuado uso de la herramienta que permite realizar el estudio dentro del Régimen del Seguro de Previsión Social (***RSPS***).

Con el presente manual se pretende que el personal de la unidad de actuaria tenga una guía para el desarrollo de la proyección del flujo de efectivo. La herramienta informática de Excel que se describe a lo largo de este manual contiene una serie de características las cuales permiten modelar esas proyecciones, cada una de ellas describe a detalle el proceso a seguir para el buen funcionamiento de esta, tomando en cuenta distintos factores tanto internos como externos que pueden afectar al régimen.

En términos generales, esta herramienta proporciona un análisis de escenarios donde se plantean distintas situaciones considerando los riesgos que estas pueden representar, a fin de tomar decisiones estratégicas y realizar mediciones de indicadores que permitan tener una visión más exacta de lo que la institución requiere para cumplir con los compromisos previamente adquiridos. Este esquema se reduce en la visualización del desfase de los tres puntos críticos considerando como escenario favorable a aquellos que dilatan la ocurrencia de estos, cabe mencionar que el primer punto crítico se da cuando los ingresos corrientes que recibe el Régimen no son suficientes para cubrir los gastos y se recurre a los ingresos financieros, el segundo punto crítico, es cuando se toma recursos del patrimonio, y el Tercer Punto Crítico, es cuando se ha consumido todo el patrimonio y ya no existen recursos para cubrir el déficit de ingresos para obtener el gasto total.